"""
app.py
KisanSetu — Phygital ONDC Marketplace Prototype (Streamlit shell)

Run with:
    streamlit run app.py

Requires: streamlit, pandas, numpy, altair, folium, streamlit-folium
    pip install streamlit pandas numpy altair folium streamlit-folium

Expects inventory.csv (generated by generate_inventory.py) in the same folder.
"""

import random
import time

import altair as alt
import folium
import pandas as pd
import streamlit as st
from streamlit_folium import st_folium

# --------------------------------------------------------------------------
# Page config — must be the first Streamlit call
# --------------------------------------------------------------------------
st.set_page_config(
    page_title="KisanSetu",
    page_icon="🌾",
    layout="wide",
    initial_sidebar_state="expanded",
)


# --------------------------------------------------------------------------
# Data loading (cached so it's read once per session unless the file changes)
# --------------------------------------------------------------------------
@st.cache_data
def load_inventory(path: str = "inventory.csv") -> pd.DataFrame:
    df = pd.read_csv(path)
    return df


try:
    inventory_df = load_inventory()
except FileNotFoundError:
    inventory_df = pd.DataFrame()
    st.sidebar.warning("inventory.csv not found — run generate_inventory.py first.")

# Working copy of inventory lives in session_state so new VLE entries persist
# across reruns/navigation without touching the on-disk CSV.
if "inventory" not in st.session_state:
    st.session_state["inventory"] = inventory_df.copy()

# Holds a produce entry that's been logged but not yet AI-graded.
if "pending_entry" not in st.session_state:
    st.session_state["pending_entry"] = None

# Holds the index of the catalogue item currently being routed (ONDC Buyer Network page).
if "routing_item_idx" not in st.session_state:
    st.session_state["routing_item_idx"] = None

# Approximate coordinates for each Village Hub (mock — for demo routing only).
HUB_COORDINATES = {
    "Barachatti Hub": (24.6499, 84.9575),
    "Tekari Hub": (24.9337, 84.8332),
    "Sherghati Hub": (24.5667, 84.7833),
    "Bodh Gaya Hub": (24.6959, 84.9910),
    "Wazirganj Hub": (24.7167, 84.9333),
    "Imamganj Hub": (24.6333, 84.6333),
    "Guraru Hub": (24.8667, 84.8667),
    "Fatehpur Hub": (24.7500, 84.9000),
}

# Generic mock ONDC buyer destination (e.g. an urban consolidation point).
ONDC_BUYER_DESTINATION = ("ONDC Buyer Hub — Patna", (25.5941, 85.1376))

LOGISTICS_PARTNERS = ["Delhivery", "Porter", "Shadowfax", "Ekart Logistics"]


# --------------------------------------------------------------------------
# Sidebar navigation
# --------------------------------------------------------------------------
st.sidebar.title("🌾 KisanSetu")
st.sidebar.caption("Phygital ONDC Marketplace")

page = st.sidebar.radio(
    "Navigate to:",
    options=["VLE Dashboard", "Mandi Analytics", "ONDC Buyer Network"],
)

st.sidebar.divider()
st.sidebar.caption("Team: The Odyssey | SIH26033")


# --------------------------------------------------------------------------
# Page: VLE Dashboard
# --------------------------------------------------------------------------
def get_reference_mandi_price(df: pd.DataFrame, crop: str) -> float:
    """
    Looks up a reference mandi price for a crop from existing inventory data
    (average of current listings for that crop). Falls back to the overall
    average price if the crop has no prior listings.
    """
    crop_rows = df[df["Crop_Type"] == crop]
    if not crop_rows.empty:
        return round(crop_rows["Current_Mandi_Price"].mean(), 2)
    if not df.empty:
        return round(df["Current_Mandi_Price"].mean(), 2)
    return 20.00  # generic fallback if no data exists at all


def render_vle_dashboard(df: pd.DataFrame) -> None:
    st.title("VLE Dashboard")
    st.caption("Village-level operator view — onboarding, weighing & catalogue creation")

    working_df = st.session_state["inventory"]

    if working_df.empty:
        st.info("No inventory data loaded yet.")
        return

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Listings", len(working_df))
    col2.metric("Total Quantity (KG)", f"{working_df['Quantity_KG'].sum():,}")
    col3.metric("Active Hubs", working_df["Hub_Location"].nunique())

    st.divider()

    # ----------------------------------------------------------------------
    # Log New Produce form
    # ----------------------------------------------------------------------
    st.subheader("📝 Log New Produce")

    crop_options = sorted(working_df["Crop_Type"].unique().tolist())
    hub_options = sorted(working_df["Hub_Location"].unique().tolist())

    with st.form("log_produce_form", clear_on_submit=True):
        f_col1, f_col2, f_col3 = st.columns(3)
        farmer_name = f_col1.text_input("Farmer Name")
        crop_type = f_col2.selectbox("Crop", options=crop_options)
        weight_kg = f_col3.number_input("Weight (KG)", min_value=1, max_value=5000, value=100, step=10)

        hub_location = st.selectbox("Hub Location", options=hub_options)

        submitted = st.form_submit_button("Log Produce")

        if submitted:
            if not farmer_name.strip():
                st.warning("Please enter a farmer name before logging produce.")
            else:
                st.session_state["pending_entry"] = {
                    "Farmer_Name": farmer_name.strip(),
                    "Crop_Type": crop_type,
                    "Quantity_KG": int(weight_kg),
                    "Hub_Location": hub_location,
                }

    # ----------------------------------------------------------------------
    # Simulate AI Grading
    # ----------------------------------------------------------------------
    pending = st.session_state["pending_entry"]

    if pending is not None:
        st.info(
            f"Pending entry: **{pending['Farmer_Name']}** — {pending['Quantity_KG']} kg "
            f"of **{pending['Crop_Type']}** @ {pending['Hub_Location']}. "
            "Run AI grading to assign a quality grade and suggested listing price."
        )

        if st.button("🤖 Simulate AI Grading"):
            with st.spinner("Running AI quality-grading model..."):
                time.sleep(2)

                grade = random.choice(["A", "B", "C"])
                mandi_price = get_reference_mandi_price(working_df, pending["Crop_Type"])
                suggested_price = round(mandi_price * 1.10, 2)  # +10% over mandi price

                new_entry = {
                    "Farmer_Name": pending["Farmer_Name"],
                    "Crop_Type": pending["Crop_Type"],
                    "Quantity_KG": pending["Quantity_KG"],
                    "Grade": grade,
                    "Current_Mandi_Price": suggested_price,
                    "Hub_Location": pending["Hub_Location"],
                }

                st.session_state["inventory"] = pd.concat(
                    [working_df, pd.DataFrame([new_entry])], ignore_index=True
                )
                st.session_state["pending_entry"] = None

            st.success(
                f"AI Grading complete — Grade **{grade}** assigned. "
                f"Suggested ONDC listing price: **₹{suggested_price}/kg** "
                f"(mandi ref: ₹{mandi_price}/kg + 10%)."
            )
            st.rerun()

    st.divider()

    # ----------------------------------------------------------------------
    # Updated inventory table
    # ----------------------------------------------------------------------
    st.subheader("All Registered Produce")
    st.dataframe(st.session_state["inventory"], use_container_width=True)


# --------------------------------------------------------------------------
# Page: Mandi Analytics
# --------------------------------------------------------------------------
def render_mandi_analytics(df: pd.DataFrame) -> None:
    st.title("Mandi Analytics")
    st.caption("Government mandi price benchmarking, ONDC price comparison & farmer profit impact")

    # Use the live (session) inventory so entries logged in the VLE Dashboard
    # show up here too.
    working_df = st.session_state.get("inventory", df)

    if working_df.empty:
        st.info("No inventory data loaded yet.")
        return

    # ------------------------------------------------------------------
    # Derive an ONDC listing price where one isn't already stored.
    # Rows graded via the VLE Dashboard already carry an ONDC-adjusted
    # Current_Mandi_Price; for a clean side-by-side comparison here we
    # keep the original mandi price separate and derive the ONDC price
    # as mandi price + 10%, consistent with the VLE grading logic.
    # ------------------------------------------------------------------
    analytics_df = working_df.copy()
    analytics_df["ONDC_Listing_Price"] = round(analytics_df["Current_Mandi_Price"] * 1.10, 2)

    # ------------------------------------------------------------------
    # Top 3 crops by total listed quantity (i.e. most-traded on the platform)
    # ------------------------------------------------------------------
    top_crops = (
        analytics_df.groupby("Crop_Type")["Quantity_KG"]
        .sum()
        .sort_values(ascending=False)
        .head(3)
        .index.tolist()
    )

    st.subheader("📊 Mandi Price vs ONDC Listing Price — Top 3 Crops")
    st.caption(f"Ranked by total listed volume: {', '.join(top_crops)}")

    comparison_df = (
        analytics_df[analytics_df["Crop_Type"].isin(top_crops)]
        .groupby("Crop_Type")[["Current_Mandi_Price", "ONDC_Listing_Price"]]
        .mean()
        .reset_index()
        .rename(
            columns={
                "Current_Mandi_Price": "Avg Mandi Price",
                "ONDC_Listing_Price": "Avg ONDC Listing Price",
            }
        )
    )

    # Reshape to long format for a grouped/clustered bar chart in Altair
    chart_df = comparison_df.melt(
        id_vars="Crop_Type",
        value_vars=["Avg Mandi Price", "Avg ONDC Listing Price"],
        var_name="Price Type",
        value_name="Price (₹/kg)",
    )

    grouped_bar = (
        alt.Chart(chart_df)
        .mark_bar()
        .encode(
            x=alt.X("Crop_Type:N", title="Crop", axis=alt.Axis(labelAngle=0)),
            y=alt.Y("Price (₹/kg):Q", title="Price (₹/kg)"),
            color=alt.Color(
                "Price Type:N",
                scale=alt.Scale(
                    domain=["Avg ONDC Listing Price","Avg Mandi Price"],
                    range=[ "#94a3b8","#16a34a"],
                ),
            ),
            xOffset="Price Type:N",
            tooltip=["Crop_Type", "Price Type", alt.Tooltip("Price (₹/kg):Q", format=".2f")],
        )
        .properties(height=380)
    )

    st.altair_chart(grouped_bar, use_container_width=True)

    st.divider()

    # ------------------------------------------------------------------
    # Farmer Profit Impact metric card
    # ------------------------------------------------------------------
    st.subheader("💰 Farmer Profit Impact")

    total_mandi_value = (analytics_df["Current_Mandi_Price"] * analytics_df["Quantity_KG"]).sum()
    simulated_kisansetu_value = total_mandi_value * 1.15  # simulated 15% uplift from bypassing middlemen
    profit_gain = simulated_kisansetu_value - total_mandi_value

    m_col1, m_col2, m_col3 = st.columns(3)
    m_col1.metric(
        "Traditional Channel Value (est.)",
        f"₹{total_mandi_value:,.0f}",
    )
    m_col2.metric(
        "KisanSetu Net Value (Simulated)",
        f"₹{simulated_kisansetu_value:,.0f}",
        delta="+15% vs middlemen channel",
    )
    m_col3.metric(
        "Additional Farmer Earnings",
        f"₹{profit_gain:,.0f}",
    )

    st.caption(
        "Simulated estimate: assumes a 15% average net-earnings uplift for farmers from "
        "direct ONDC market access versus traditional intermediary-based selling. "
        "Based on current session inventory value (Σ Quantity × Mandi Price)."
    )

    st.divider()

    # ------------------------------------------------------------------
    # Existing crop-level browsing tools
    # ------------------------------------------------------------------
    crop_filter = st.selectbox(
        "Select Crop Type", options=["All"] + sorted(analytics_df["Crop_Type"].unique().tolist())
    )
    filtered = analytics_df if crop_filter == "All" else analytics_df[analytics_df["Crop_Type"] == crop_filter]

    st.subheader("Average Mandi Price by Crop")
    price_by_crop = filtered.groupby("Crop_Type")["Current_Mandi_Price"].mean().sort_values(ascending=False)
    st.bar_chart(price_by_crop)

    st.subheader("Price Distribution Table")
    st.dataframe(filtered, use_container_width=True)

    # TODO: integrate live AGMARKNET API feed
    # TODO: replace simulated 15% profit uplift with real farmer-reported earnings data


# --------------------------------------------------------------------------
# Page: ONDC Buyer Network
# --------------------------------------------------------------------------
def simulate_ai_routing(item: pd.Series) -> None:
    """Runs a mock AI logistics routing simulation for the given catalogue item."""
    st.divider()
    st.subheader(f"🚚 AI Logistics Routing — {item['Crop_Type']} from {item['Farmer_Name']}")

    progress_bar = st.progress(0, text="Calculating optimal route...")
    stages = [
        (20, "Checking hub inventory..."),
        (45, "Matching nearest logistics partner..."),
        (70, "Calculating shortest route..."),
        (90, "Estimating delivery time..."),
        (100, "Route confirmed."),
    ]
    for pct, label in stages:
        time.sleep(0.3)
        progress_bar.progress(pct, text=label)

    # --- Mock routing outputs -------------------------------------------------
    logistics_partner = random.choice(LOGISTICS_PARTNERS)
    delivery_time = random.choice(["4-6 hours", "8-12 hours", "1 Day", "1-2 Days"])
    distance_km = round(random.uniform(35, 120), 1)

    st.success(
        f"✅ Order routed successfully!\n\n"
        f"**Logistics Partner:** {logistics_partner}  \n"
        f"**Estimated Delivery Time:** {delivery_time}  \n"
        f"**Approx. Route Distance:** {distance_km} km"
    )

    # --- Mock route map --------------------------------------------------------
    origin_name = item["Hub_Location"]
    origin_coords = HUB_COORDINATES.get(origin_name, (24.7, 84.9))  # fallback near Gaya
    dest_name, dest_coords = ONDC_BUYER_DESTINATION

    route_map = folium.Map(
        location=(
            (origin_coords[0] + dest_coords[0]) / 2,
            (origin_coords[1] + dest_coords[1]) / 2,
        ),
        zoom_start=8,
        tiles="cartodbpositron",
    )
    folium.Marker(
        origin_coords, tooltip=origin_name, popup=origin_name,
        icon=folium.Icon(color="green", icon="leaf"),
    ).add_to(route_map)
    folium.Marker(
        dest_coords, tooltip=dest_name, popup=dest_name,
        icon=folium.Icon(color="blue", icon="shopping-cart"),
    ).add_to(route_map)
    folium.PolyLine(
        [origin_coords, dest_coords], color="#16a34a", weight=4, dash_array="8",
    ).add_to(route_map)

    st.caption(f"Generic route preview: {origin_name} → {dest_name} (via {logistics_partner})")
    st_folium(route_map, use_container_width=True, height=380, key="routing_map")

    if st.button("Close routing panel"):
        st.session_state["routing_item_idx"] = None
        st.rerun()


def render_ondc_buyer_network(df: pd.DataFrame) -> None:
    st.title("ONDC Buyer Network")
    st.caption("Catalogue discovery & order flow for participating ONDC buyer apps")

    working_df = st.session_state.get("inventory", df)

    if working_df.empty:
        st.info("No inventory data loaded yet.")
        return

    # ------------------------------------------------------------------
    # Search & filters
    # ------------------------------------------------------------------
    search_col, hub_col, grade_col = st.columns([2, 1, 1])
    search_term = search_col.text_input("🔍 Search by crop or farmer name", "")
    hub_filter = hub_col.multiselect(
        "Hub Location", options=sorted(working_df["Hub_Location"].unique().tolist())
    )
    grade_filter = grade_col.multiselect(
        "Grade", options=sorted(working_df["Grade"].unique().tolist())
    )

    filtered = working_df.copy()
    if search_term:
        mask = (
            filtered["Crop_Type"].str.contains(search_term, case=False, na=False)
            | filtered["Farmer_Name"].str.contains(search_term, case=False, na=False)
        )
        filtered = filtered[mask]
    if hub_filter:
        filtered = filtered[filtered["Hub_Location"].isin(hub_filter)]
    if grade_filter:
        filtered = filtered[filtered["Grade"].isin(grade_filter)]

    st.subheader(f"🛒 Available Catalogue ({len(filtered)} listings)")

    if filtered.empty:
        st.warning("No listings match your search/filters.")
    else:
        # ------------------------------------------------------------------
        # E-commerce-style catalogue cards
        # ------------------------------------------------------------------
        for idx, row in filtered.iterrows():
            with st.container(border=True):
                c1, c2, c3, c4 = st.columns([3, 2, 2, 2])
                with c1:
                    st.markdown(f"**{row['Crop_Type']}**")
                    st.caption(f"Sold by {row['Farmer_Name']} · {row['Hub_Location']}")
                with c2:
                    st.metric("Grade", row["Grade"])
                with c3:
                    st.metric("Qty (kg)", f"{row['Quantity_KG']:,}")
                    st.caption(f"₹{row['Current_Mandi_Price']:.2f}/kg")
                with c4:
                    if st.button("🛍️ Buy & Route", key=f"buy_{idx}"):
                        st.session_state["routing_item_idx"] = idx

    # ------------------------------------------------------------------
    # If an item was selected, run the AI routing simulation for it
    # ------------------------------------------------------------------
    routing_idx = st.session_state["routing_item_idx"]
    if routing_idx is not None and routing_idx in working_df.index:
        simulate_ai_routing(working_df.loc[routing_idx])

    # TODO: integrate Beckn protocol seller APIs for real ONDC listing & order placement
    # TODO: replace mock routing outputs with real logistics-partner API integration


# --------------------------------------------------------------------------
# Route to selected page
# --------------------------------------------------------------------------
if page == "VLE Dashboard":
    render_vle_dashboard(inventory_df)
elif page == "Mandi Analytics":
    render_mandi_analytics(inventory_df)
elif page == "ONDC Buyer Network":
    render_ondc_buyer_network(inventory_df)
